### ISSUE TITLE
Error when uploading extension with caps like .ZIP

### ISSUE THREAD

**Issue by francdore** [moxiecode/plupload#1501] opened 2017-07-31 07:13 UTC
Hi,

I'm getting an error when uploading a file with an uppercase extension like .ZIP.

Is there an option for the plugin to cater for this?

Thanks!

**Comment by jayarjo** [comment] 2017-08-04 16:31
What plupload version do you use? And what is the error you encounter?

**Comment by jayarjo** [comment] 2017-08-25 17:31
I cannot reproduce it in 2.3.1, so I guess I will close this for now. Feel free to re-open, with more details or [fiddle](http://play.plupload.com).

**Closed** 2017-08-25 17:31 UTC
Labels: Requires more info
