### ISSUE TITLE
xhr object not existing for some reason

### ISSUE THREAD

**Issue by Setitch** [moxiecode/plupload#1056] opened 2014-04-19 11:59 UTC
2.1.1 - line 1376 (dev version).

``` js
                try {
                    if (xhr.status >= 400) {
                        handleError();
                        return;
                    }
                } catch (e) {
                    return ;
                }
```

Im canceling uploads when i got confirmation from the server that same file was already received... (I count hash codes for EACH chunk of the file, and then sends all chunk hashes to the server. Server responds with ,,continue'' ,,already there'' comments - and i allows uploads to be continue or halts the upload of certain file. However i sometimes (probably) when canceling, the xhr is still returning but as null. Therefore adding this try...catch block helped with the project.

If i finish project i may publish it code in the future.

**Comment by aik099** [comment] 2015-04-29 10:00
This sounds like duplicate of #1179.

**Comment by Setitch** [comment] 2015-04-29 10:02
How it can be duplicate of something that was created AFTER?

**Comment by aik099** [comment] 2015-04-29 10:05
When I choose duplicates I pick as original issue the one, that has more info on a subject, not the one, that was created earlier.

**Comment by Setitch** [comment] 2015-04-29 10:18
Maybe we all should use some strange methods for duplication? If something is duplicating other - that means the other is newer than the original one. So maybe stick to the definitions and not make your own?  -  just not random thought.

Also this issue is still available on newer version of the library than i had reported - so no one even tried to fix that.  (PS: I contacted moxie by mail - but got ignored totally).

**Comment by aik099** [comment] 2015-04-29 10:26
> Maybe we all should use some strange methods for duplication? If something is duplicating other - that means the other is newer than the original one. So maybe stick to the definitions and not make your own? - just not random thought.

I do, what I think best for a project. I think, that duplicates, that provide less intel should be closed to prevent too much noise in issue list. This way the issue, that stays (regardless of creation date) has most valuable intel to reproduce the problem or has some valuable fixing solution.

Jumping between issue and it's duplicates to figure out all needed info doesn't seem a productive approach to me, but I guess you like it better :wink: 

> Also this issue is still available on newer version of the library than i had reported - so no one even tried to fix that. (PS: I contacted moxie by mail - but got ignored totally).

I'm aware of that, which is explained in my latest comment: https://github.com/moxiecode/plupload/issues/1179#issuecomment-97377585

**Closed** 2017-08-28 08:25 UTC
Labels: Fixed in coming release
