### ISSUE TITLE
HTML5 FileUploaded response.status returns 0

### ISSUE THREAD

**Issue by skovhus** [moxiecode/plupload#778] opened 2013-04-26 19:59 UTC
We are happily using Plupload 1.5.6 for thousands of upload every day. Primary using the HTML5 runtime, but also Flash as a fallback.

But we have a few users experiencing persistent problems with uploading using the HTML5 runtime. We have detected these problems, as we in the 'FileUploaded' event check the value of the response.status. If the status code is 0, we retry the entire upload a couple of times. In our logs we see the same users trying to upload several times, but without any luck. No files hit our upload servers. It looks like the problems show up on Opera, Safari, Firefox and Chrome (we haven't seen the issue on IE yet). 

First we thought of CORS problems, as the NGINX upload servers are on a cross origin domain... But we cannot find any errors in the upload server configuration. And when investigating our NGINX backend we never see a HTTP OPTIONS or HTTP POST for these users, although Plupload reports that the file was uploaded. 

To figure out what the problem was, we extended our client code to test uploading a file without using Plupload for the users where FileUploaded returned response.status===0. The code  expects that the user has XHR and FormData support:

``` javascript
function testCallingCrossOrigin(server, id){
    var logReport = [];
    try {
        var xhr = new XMLHttpRequest();
        var url = 'http://' +server+ '/upload?id=' +id;

        if(xhr) {
            xhr.open('post', url, true);

            xhr.onreadystatechange = function() {
                var parsedHttpStatus;
                try {
                    parsedHttpStatus = xhr.status;
                } catch (ex) {
                    parsedHttpStatus = ex;
                }

                var parsedReadyState;
                try {
                    parsedReadyState = xhr.readyState;
                } catch (ex) {
                    parsedReadyState = ex;
                }

                logReport.push({
                    parsedHttpStatus: parsedHttpStatus,
                    parsedReadyState: parsedReadyState
                });

                if (xhr.readyState === 4 || xhr.readyState === 0) {
                    sendLogReport();
                }
            };

            if (!!window.FormData) {
                var formData = new FormData();

                // Add fake file and send it
                var oFileBody = '<fake></fake>';
                var oBlob = new Blob([oFileBody], { type: 'text/xml'});
                formData.append('file', oBlob);

                xhr.send(formData);
            } else {
                // no formdata, plupload will send as binary
                logReport.push('No window.FormData, no test');
                sendLogReport();
            }
        } else {
            logReport.push('No xhr, no test');
            sendLogReport();
        }

    } catch (ex) {
        logReport.push(ex.message);
        sendLogReport();
    }

    function sendLogReport() {
        // INSERT CODE FOR REPORTING ERROR TO BACKEND
    }
}
```

To our surprise it looks like the testCallingCrossOrigin successfully uploads to our backend, although Plupload fails...  

Our Plupload options look like this:

``` javascript
var options = {
    'runtimes': 'html5,flash',
    'max_file_size': '100mb',
    'multi_selection': true,
    'flash_swf_url': *OMITTED*,
    'browse_button' *OMITTED*,
    'drop_element': *OMITTED*,
    'container': *OMITTED*,
    'filters': [
        *OMITTED*
    ]
};
```

Our detection code for status === 0 in the FileUploaded event:

``` javascript
plUploader.bind('FileUploaded', function(up, file, response) {
    if (response && response.hasOwnProperty('status') && response.status === 0) {
        // custom recovery of the upload
    } ...
```

Currently we solve the problem by restarting Plupload using the Flash runtime... So when we detect that a client has failed to retry the upload and got response.status===0 several times, we ask them to select the file again using Flash runtime. This seems to work fine. But we would like a more permanent solution for HTML5. Do you have any suggestions or things we should try out?

**Comment by daflip** [comment] 2015-03-29 11:52
Still seeing this bug .. it appears the issue is related to keep alives on the server. When closing a keep alive'd connection the upload "channel" in webkit is also closed and this causes 'http error 0'.  Very odd

**Comment by Xavier-Lam** [comment] 2015-05-27 05:45
I met this bug too....I only met this problem when multi-upload files. In method "FileUploaded" I removed file which success uploaded from queue.
'FileUploaded': function(up, file, info) {
        up.removeFile(file);
},

**Comment by jayarjo** [comment] 2017-08-06 12:45
Related: https://github.com/moxiecode/plupload/issues/240

**Comment by jayarjo** [comment] 2017-08-06 12:47
In theory this should be handled gracefully by the browser itself. But I've added a condition to consider all HTTP statuses below 200 as errors as well. Just in case.

**Closed** 2017-08-28 08:24 UTC
Labels: Fixed in coming release
