### ISSUE TITLE
Duplicated file added during file upload

### ISSUE THREAD

**Issue by Pellay** [moxiecode/plupload#1093] opened 2014-07-04 10:43 UTC
It does not matter if the duplicate file is not the current file being uploaded from the queue. If a duplicate file is detected it stops the current file upload and moves to the next. 

```javascript
function onError(up, err) {}
```
Does not check err.code 602 plupload.FILE_DUPLICATE_ERROR
and just presumes the file failed and moves to the next

Also it might be useful to return the 'duplicate file' as well as the 'current file' in order to identify the file within the queue using duplicateFile.id 

```javascript
plupload.addFileFilter('prevent_duplicates', function(value, file, cb) {
	if (value) {
		var ii = this.files.length;
		while (ii--) {
			// Compare by name and size (size might be 0 or undefined, but still equivalent for both)
			if (file.name === this.files[ii].name && file.size === this.files[ii].size) {
				this.trigger('Error', {
					code : plupload.FILE_DUPLICATE_ERROR,
					message : plupload.translate('Duplicate file error.'),
					file: file,
					duplicateFile: this.files[ii]
				});
				cb(false);
				return;
			}
		}
	}
	cb(true);
});
```

**Comment by najamelan** [comment] 2015-03-18 00:47
I can confirm this problem. If it turns out to be in onError, I'll try to make a pull request.

**Comment by jayarjo** [comment] 2015-03-19 12:45
@Pellay, if file is duplicate then `duplicateFile` will be duplicate of `file` property. What's the point?

**Comment by Pellay** [comment] 2015-03-19 12:51
Sorry, it's been a long time since I modified this. If I recall correctly it is the file.id that is different. File returns the file I just tried to add to the queue, while duplicateFile returns the file already in the queue. I was able to then highlight the duplicate file to show that is was already in the queue to the end user.

**Comment by najamelan** [comment] 2015-03-19 14:50
I think commit bb0a39a should fix the issue at hand. I just wonder how this plays with "retries".  Until now plupload did retry on response codes other >= 400, which might not always be appropriate, eg. 406 means 'unacceptable' which probably means the server rejects it for reasons of size or extension, which probably means reuploading it is just a waste of bandwidth, where as 400 means bad request which maybe means there is some network problem involved. Response 500 as well might benefit from retrying. 

Ok, I now see that HTTP_ERROR only get's thrown after retrying, so this probably has no influence on that.

**Closed** 2015-03-19 18:12 UTC
