### ISSUE TITLE
Chrome Error with Flash

### ISSUE THREAD

**Issue by gnxrob** [moxiecode/plupload#595] opened 2012-08-04 22:41 UTC
Uploading directly to S3, there is an issue with Chrome's Flash.  Amazon returns a '201 Created' response to Chrome, but somehow the flash front-end thinks it's an error and throws an error #2038.

Files are uploaded fine to S3.  This does not occur in other browsers/platforms.

**Comment by jayarjo** [comment] 2017-08-20 12:37
Closing as duplicate of #594.

**Closed by jayarjo** 2017-08-20 12:37 UTC
Labels: Duplicate
