### ISSUE TITLE
Resize image with poor quality

### ISSUE THREAD

**Issue by nsynsynsy** [moxiecode/plupload#1330] opened 2016-01-02 02:39 UTC
How to improve the quality of resized image? the image looks "aliasing", I set the quality from 80 to 100, nothing changed. The quality of image looks terrible after resize...

**Comment by dazbradbury** [comment] 2016-05-06 09:52
This is a duplicate of: https://github.com/moxiecode/plupload/issues/707

**Closed** 2016-11-09 10:54 UTC
Labels: Duplicate
