### ISSUE TITLE
Resize images - poor quality

### ISSUE THREAD

**Issue by robfaas** [moxiecode/plupload#707] opened 2013-02-07 09:33 UTC
(also posted in forum on plupload.com)
After trying, buying and working days to implement Plupload 2 properly I am very unpleasantly surprised by the poor quality of resized images.
It is not obvious on all photos, so I missed it at first. But on a lot of images you cannot ignore it. My goal is to use it for photography sites, so this is really not working good enough.
(And before you suggest resizing on server; that way full size images have to be uploaded, this takes far too much time.)

It appears to happen in all runtimes (Flash, Silverlight and HTML5). Example: http://www.anothersite.nl/plupload.jpg - left=original, right=resized

I don't know how the client side resizing is done, but I do know that the wrong resample method is used! The used method preserves the hard edges. Programs like Photoshop or Irfanview offer different good methods for resampling.

So, my question: is it possible to use another, better method for (client side) resampling?

**Comment by matthiaswagnerwy** [comment] 2015-02-18 10:35
@jayarjo, is there any chance to see improvements in a release soon? you mentioned above that you could make a release for oem-clients. although i'm not, i think many people here would make a donation for this feature ;)

**Comment by futureweb** [comment] 2015-02-18 10:38
We still would be very interested in integrating PLUPLOAD in our CMS ... but can't integrate it yet as the picture Quality is still too bad ... Hope to see some improvements here soon ...

Andreas Schnederle-Wagner
http://www.futureweb.at

**Comment by robfaas** [comment] 2015-02-18 11:02
The same here!

**Comment by matthiaswagnerwy** [comment] 2015-02-18 13:06
in the meantime you can have a look at the hint from @rob-z above. took me two hours now to turn off pluploads resizing and generate different versions of the uploaded pic with that solution (including soze, greyscale, watermark, ...). only thing is that processing is a bit slow imho.

**Comment by roman02** [comment] 2015-03-01 15:05
If development of this has stalled, an alternative is needed. Does anyone know of any?

**Comment by robfaas** [comment] 2015-03-19 07:48
Maybe https://github.com/mailru/FileAPI (I have not tested for quality of resized images yet)

**Comment by roman02** [comment] 2015-03-20 17:07
Thank you, @robfaas . That solution seems to be maintained. http://mailru.github.io/FileAPI/ contains demos.

**Comment by robfaas** [comment] 2015-03-20 17:42
Yes @roman02. I just tested with the same image I used on Plupload: http://www.anothersite.nl/plupload.jpg and FileAPI http://www.anothersite.nl/fileapi.jpg seems to do allright where Plupload failed! I think the guys of Plupload are not that interested in improving their product...

**Comment by straube** [comment] 2015-03-20 18:03
Hey @robfaas. Since you are already trying that lib, can you say if is it easy to replace Plupload by FileAPI in an existing project? I've seen the docs, but I'm not sure about that.

**Comment by robfaas** [comment] 2015-03-20 20:30
Sorry @straube, don't know, I just tested it with the online demo.

**Comment by roman02** [comment] 2015-03-21 07:17
Thanks for testing it for us! Saves us time.

**Comment by robfaas** [comment] 2015-03-21 08:07
I just tested with one (difficult) image. You can try for yourself: http://mailru.github.io/FileAPI/examples/thumbnails.html

**Comment by pavelvasev** [comment] 2015-08-08 12:14
It seems FileAPI is too big enough. 

And it seems that there is another project targeted specially to image resizing, which looks well: https://github.com/nodeca/pica

See demo: http://nodeca.github.io/pica/demo/

I can try to embed `pica` to `plupload` as a selectable option, but I need to ask Moxiecode people could they will grant me license for `plupload` for my commercial projects instead? (those are not MS, believe;)) @jayarjo  ?

**Comment by futureweb** [comment] 2015-08-10 14:42
As there is no real progress visible - I switched my Uploader to this one: http://www.albanx.com/ajaxuploader/index.php ... pretty good Image Quality and good Performance ...
Just in case someone is looking for some alternative too ...

Andreas

**Comment by avalanche1** [comment] 2015-10-19 08:50
For quality img resizing I highly recommend Pica - https://github.com/nodeca/pica

**Comment by roman02** [comment] 2015-11-17 04:42
Thank you, @futureweb

**Comment by robfaas** [comment] 2015-11-17 08:00
I agree with @avalanche1 that Pica does a great job. I tested it with a difficult photo (thin hairlines + high contrast) and it worked fine. When integrated in Plupload or Blueimp - https://github.com/blueimp/jQuery-File-Upload, these would become perfect uploaders.

**Comment by ml48603** [comment] 2016-03-18 21:01
I am interested in wuservices solution posted on Feb 7, 2013 about opting to not use resizing in plupload .  How do I disable file resizing globally in PLUpload ? I have installed v 2.1.8 on a test server and am trying to get the bugs worked out and reconfigurations in place.

**Comment by jayarjo** [comment] 2016-03-19 20:56
I've just merged in a branch with better quality resizing for the Flash runtime (https://github.com/moxiecode/moxie/commit/e63c4efcd7081401079e2ca786a50f5b51517801). It uses Pixel Bender, some simple shaders and gradual scaling.

**Comment by jayarjo** [comment] 2016-03-19 21:01
@ml48603, simple solution would be to simply not use `resize` option in your Plupload config. More sophisticated way includes custom compiling with exclusion of the image manipulation module and using of our mini versions of Flash and Silverlight shims, that do not have image related code in them, and weight much less. You can find them in the bin/ folder of the underlying moxie project [here](https://github.com/moxiecode/moxie/tree/master/bin).

**Comment by jayarjo** [comment] 2016-03-19 21:03
If you guys can suggest difficult photos for me to test, please do.

**Comment by Gangkaroo** [comment] 2016-03-20 14:39
Great to see that work is done in this area of the project. As robfaas indicated, photos with thin lines that have a high contrast are a good indicator (dark hair on a white background for example).

**Comment by jayarjo** [comment] 2016-03-20 17:10
Here is the resizing with updated Flash runtime:

* Default:
![default](https://cloud.githubusercontent.com/assets/150075/13905657/ac239f30-eedf-11e5-9154-5940f6418b2a.jpeg)

* Bilinear resampling:
![bilinear](https://cloud.githubusercontent.com/assets/150075/13905656/ac1df292-eedf-11e5-8595-c629f6c36d39.jpeg)

Original image can be found [here](http://www.anthonymorganti.com/wp-content/uploads/2015/01/Short-Curly-Hair-copy.jpg) (random image from the Google).

**Comment by robfaas** [comment] 2016-03-21 07:25
Here is one to test: http://www.anothersite.nl/testphoto.jpg

**Comment by jayarjo** [comment] 2016-05-02 11:55
@robfaas, Downsized to 222x300.

* Default (old):
![flash_nearest_neighbour](https://cloud.githubusercontent.com/assets/150075/14953787/f092526e-107d-11e6-968c-569c6d0c93a6.jpeg)

* Default:
![flash_default](https://cloud.githubusercontent.com/assets/150075/14953789/f0956e90-107d-11e6-898d-625c9853c2cd.jpeg)

* Bilinear:
![flash_bilinear](https://cloud.githubusercontent.com/assets/150075/14953788/f0924a26-107d-11e6-83eb-8dfb423205b5.jpeg)

**Comment by robfaas** [comment] 2016-05-02 12:08
@jayarjo That's a good result! Bilinear is allright, but softened the original to much. I think the new Default is the best.

**Comment by dzymail** [comment] 2016-05-05 23:56
when we can use this new feature?  really need this! :+1: 
I like show resizing file final size immediately after file selected,  like [https://github.com/blueimp/jQuery-File-Upload](jquery file upload) do.

**Comment by jayarjo** [comment] 2016-05-06 09:04
@dzymail we cannot know what the exact size will be before we do the resizing. We can approximate (roughly), or resize the images right after selection (which might be an option I think). I do not know what jQuery-File-Upload does, can you arrange the demo (of the feature you've mentioned)?

**Comment by jayarjo** [comment] 2016-05-06 09:06
This has become a frequently requested feature, so I guess I need to implement it... one way or another.

**Comment by dzymail** [comment] 2016-05-19 12:16
jquery-file-upload had this demo link: https://blueimp.github.io/jQuery-File-Upload
1. click "add files" button, select a big image file (about 2M).
2. then before we upload, file size show as 400k , not 2M.
3. click upload, finish it.

**Comment by jayarjo** [comment] 2016-06-08 08:42
From what I see, it looks like `jquery-file-upload` pre-resizes image to get the final size and then resizes again..?

**Comment by danrossi** [comment] 2016-06-14 11:16
Hi guys I can confirm Pica provides much better quality than browser based implementations. They have a webgl option but there is an issue with the shader with aliasing so it may work eventually. WebGL would be even faster. It uses workers for scheduling. The resampling seems to need to do a huge loop through pixel by pixel on the imagedata. 

I've had to do an upload feature for S3 where I have to resize 4 different size options. But it has to re-request an upload queue and resize. It would be nice to queue each different size and upload all at once ? 

The demo for pica is here http://nodeca.github.io/pica/demo/

Code example is 

```
src = //get canvas
src.getContext("2d").drawImage(image,0,0);

dst = //dest canvas
dst.width = wiifh;
dst.height = height;

window.pica.resizeCanvas(src, dst, {
    quality: quality,
    alpha: alpha,
    unsharpAmount: unsharpAmount,
    unsharpRadius: unsharpRadius,
    unsharpThreshold: unsharpThreshold,
    transferable: true
  }, function (err) {
     //do more resize options after the first one sequentially. 
});

**Comment by cdphil** [comment] 2016-07-13 12:10
Hi,
Has this been pushed live? We have downloaded the latest version of plupload and are still experiencing quality issues. If not is this ready for us to pull and use in a live environment?

**Comment by jayarjo** [comment] 2016-09-07 04:49
Plupload 3.0-beta1 is [out now](https://github.com/moxiecode/plupload/releases/tag/v3.0-beta1). We also think to back port resampling stuff to Plupload 2.x branch,'cause Plupload 3 is basically ground up rewrite.

**Comment by jayarjo** [comment] 2016-11-14 20:25
I've backported image resizing improvements to v2.x branch. [v2.2.0](https://github.com/moxiecode/plupload/releases/tag/v2.2.0) stable is out now.

**Closed by jayarjo** 2016-11-14 20:25 UTC

**Comment by farflungideas** [comment] 2016-11-15 17:41
This is awesome! Tried to implement the new version, however, if you take a large image and set the height / width parameters, it doesn't scale the image evenly (like the old version did). 

eg. I upload an image of size: 5054 x 3370

Then set plupload up as such:

resize: { width: 1008)
                , height: 1512)
                , quality: 95
                , preserve_headers: false
            },

plupload resizes the file to: 1511 x 1007... Which is not expected.

**Comment by jayarjo** [comment] 2016-11-16 07:04
@farflungideas I guess we better file it as separate ticket.

**Comment by robfaas** [comment] 2016-11-16 07:55
@jayarjo Still have to test the quality, but I presume it will be a lot better.
And now maybe you wanna change the text in the Intro on http://www.plupload.com/docs/v2/Image-Resizing-on-Client-Side :)

**Comment by jayarjo** [comment] 2016-11-16 07:58
@robfaas there's a newer page (in the works) hiding: http://www.plupload.com/docs/v3/Image-Resizing-on-Client-Side. But yes, still need to modify that intro a bit.

**Comment by ciganox** [comment] 2016-11-21 22:35
jayarjo .... 
Thanks a lot for the work, I'm crazy to test, the quality is very important to me, plupload is the best, I hope it is implemented bicubic too
(google translate)

**Comment by jayarjo** [comment] 2016-11-22 08:03
@ciganox we did bicubic, but it turned out to be too slow to be usable. And definitely almost meaningless to port to other runtimes.

**Comment by ciganox** [comment] 2016-11-22 10:11
@jayarjo Right, but bicubic would not have more quality? Or is it little difference?
Has it taken so long that it can not be used? Can not be implemented with an option, with an observation about the conversion time? tks

**Comment by ciganox** [comment] 2016-12-01 22:11
hi
Is it implemented "bilinear" in version 2.2.1?
I did not notice any difference when using:
Resize: {width: 1500, height: 1500, quality: 90, resample: 'bilinear'}

tks

**Comment by ciganox** [comment] 2016-12-01 22:11
@jayarjo 

hi
Is it implemented "bilinear" in version 2.2.1?
I did not notice any difference when using:
Resize: {width: 1500, height: 1500, quality: 90, resample: 'bilinear'}

tks

**Comment by jayarjo** [comment] 2016-12-02 06:55
Difference will be noticeable only when you do a dramatic resize (like several times smaller, or - larger). Otherwise it should feel the same (it is expected), since browsers do use bilinear by default these days,

**Comment by ciganox** [comment] 2016-12-02 14:06
@jayarjo The original image has 5575x3717, I am decreasing to 750x500, it has no difference using "bilinear" ... using version 2.2.1
I noticed that in the code of this version, in the file plupload.full.min.js ... I did not find anything referring to "bilinear" ... already in the code of version 3 there are references to "bilinear" ...
Is it not that I downloaded a version 2.2.1 that does not have 'bilinear'?

Thank you for your willingness to clarify my questions.

(Google translator, sorry)

**Comment by jayarjo** [comment] 2016-12-02 21:31
What are you comparing to?

**Comment by ciganox** [comment] 2016-12-06 13:32
@jayarjo 
I am comparing version 2.1.9 with 2.2.1 ...
What about bilinear code? I did not find in version 2.2.1 only in version 3

**Comment by ciganox** [comment] 2016-12-06 13:55
Default
![testphoto-default](https://cloud.githubusercontent.com/assets/5252293/20927662/b763e516-bba9-11e6-9451-1e63f287e065.jpg)

Bilinear
![testphoto-bilinear](https://cloud.githubusercontent.com/assets/5252293/20927680/c7718274-bba9-11e6-9b7d-2318d1f4a678.jpg)

Downsized to 222x300.

Is correct ? No difference, the example you posted had difference between default and bilinear
tks

**Comment by jayarjo** [comment] 2017-08-09 08:55
@ciganox v2.x and v3.x both use the same version of moxie. Image resizing logic is in moxie,not in Plupload. So they are using the same thing. 

`default` is basically - `bilinear`, since in flash/silverlight almost the same result. `nearest`, which is nearest neighbour and wasn't enabled in html5 runtime until now (not sure why I forgot that), is 3-5 times faster and perfect for thumbs for example.
