### ISSUE TITLE
Problems with ShowModalDialog (IE)

### ISSUE THREAD

**Issue by mizokunimito** [moxiecode/plupload#336] opened 2011-07-29 15:25 UTC
Opening pages using ShowModalDialog method (available only in IE), the browsing files window doesn't appear.
Current runtime is flash.
The same page opened directly works fine.
To reproduce the issue simply create a page with a button and on the onclick event open the Custom Upload Example address 
(
window.showModalDialog("http://www.plupload.com/example_custom.php");
) 
and the try to click on "select files".

I'm currently using IE9.

**Comment by jayarjo** [comment] 2017-08-07 06:16
Closing this as duplicate of: https://github.com/moxiecode/plupload/issues/102.

**Closed** 2017-08-07 06:16 UTC
Labels: Duplicate
